apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: agentllm
  namespace: b4mad-machdenstaat-oparl-lite-stage
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgBKhs9yA4TLtOh5YMnBKs/ZasL9oIBvX7bubbaut4k9jGuwRUjCh3yr95By1YBLd81ktXJ2yUONafbJ47FEeu4xfB+NQ2vvPe7RFSy+4JW8X4b+ItBDvio+ekZ3fgGdcRiiO+TIJXjnzzT7hVUNDk6Vx8ZHGC/6L+1lBZMhoDtRcoLxDlq3Uh4SaToLTvoXsD9gHAm8s/sg4WCBkTBXxyN+CGA6XNpJ4bcw+n9N23uripzswStZAqvHR63WFo1nr2ILNtU4Mv/aH5fyS2C2s5vNDbnwH9Rd7QhIo0HDfLDKaSJkIZFPNYbMG9FHPlD8mmE9rkm62pY/EzzJSrbivpvRQd2E1eJ/0MYy0vUxEaGeqi2gM7nQYnls1V/5jcOOMbROnoxIR6ml3Sjndd9xBppwL/m38CLiKRHI2kPGi3jD9bIRx0ZM0r5bi742F85TIjcrI5IfaAou6g1zntzVGM8C9l2dJpw/zkgCAKsBBX9MLB6czZ1XiMCLZ+1/1EquimIsatg21OJpVhB/Z8TgvZdRfaxea56j0oLq60Bdcto2tSSNZNiNHnNc+uB1RE1ILfYrYF2gU38pZztM141M00GInHiSQnLVui/TUGmpo3ielxk7utXSjFC3CTVJyYO0FCPo4eHPA6xvNw71s40xAJT1CCylxFaPG4RT6sO3GRaVthHbtg4Ap+Qaio/JLklooXMbn14nZkjRwH+9BfBOwfcTSNn0zrQ78blr7qMFZ/lwHjc3YhBpIkhJB0m1fg49dodNNmxrNVHCAIfwipGyHN+hisMJ2Z6I5AA2YtUSiaXzL/vWKXA+1vu+YYvDLC38UdwmacsTI8GGkPyaAp8=
    OPENROUTER_API_KEY: AgCo/1lJNtk1hcDSkm92Smb1pTrR3I9A0NNMo6Bw7iQLRjTfPS2J0hxlf+PGxUDAMtg1IIAxzSgifxa5ssNNxIvlYN26rZA4ySlTBaX5+clkEO+l8wsS2rF8MTo0TYlwRXXSnSJ/6SHXlLwt/iCpT7QBKvO2cuU4d2zDmYMO2DabiRY4U0JZXmwpzFVhZKPxtF2oXNxjtoxjyhPldh99VyrHDnQBZjmxTPEjwe33435g84eJjTZ/YB58PHFXWdNtvg7qj/LlDZyHBDurDv1XwThbZMV3G3lh83kipz+tXqjiBfFL61blK8HZkPoVAe0JsEXEIYN/zrp9/T/ies1xxq4tJMUjLpK9hxRunSji4lHzj6XeIKobKHE501NI8vKDUGm2Ax6u7lx9S/Wd9etdcdoEMq5a4HbDROZPIPevPZvqrmj4K3aqhxuzq0IKg85G4cU07XtzR+TZENljv4ASeC/Cj2NtyiO7FPcXNselLpzNuxL2JyLsWbiTHG971XLJ1obmOBh2EZObWt74bpyP4cRNGDFElPTjgqoBeL+Mqq9gneKXwJBoqN/XssyIsh0u/5dB67lWv5mnNDLqPvXVnUJ/ODMoNKWzO/rP5XsG3XT2VkdTkbtSdq0Ikzooi3L0I1Q/1APgdGy3BeVDXlg/Syf6e31aSngsGwCrXErISyWMUev+5AWsC+l8b97D6mYDJI5MoaJteahJ/OhxVsX4IddTGTgHQU7Ez+4A48UAbQxO+huMMjWy+QSF9xdLqyzg21MtfErrbdideRow6TZg6Srvq6l02DuTtemC
  template:
    metadata:
      creationTimestamp: null
      name: agentllm
      namespace: b4mad-machdenstaat-oparl-lite-stage
    type: Opaque
---
